includeSuites:
  - openshift-tests
  - openshift-tests-upgrade
  - BakckendDisruption
  - Cluster upgrade
  - hypershift-e2e
  - cluster install
  - Operator results
  - Symptom Detection
  - perfscale-cdv2
  - perfscale-nd
  - perfscale-crd
  - chaos-krkn
  - telco-verification
  - OLM-Catalog-Validation
  - insights-operator-tests
  - CNV-lp-interop
  - Quay-lp-interop
  - OpenshiftPipelines-lp-interop
  - ServiceMesh-lp-interop
  - Serverless-lp-interop
  - ODF-lp-interop
  - MTA-lp-interop
  - Gitops-lp-interop
  - ACS-lp-interop
  - OADP-lp-interop
excludeSuites: []
excludeTests:
  - "Build image%"
  - "Find the input image%"
  - "Find all of the input images%"
  - "step graph.%"
  - "Run multi-stage test %"
  - "% was not OOMKilled%"
  - "Create the release image%"
  - "Import the release payload %"
  - "All images are built%"
  - "Tag the image %"
  - "%XXXitoring%"
  - "[sig-arch] Monitor cluster while tests execute"
includeJobs:
  - "periodic-%"
  - "release-%"
  - "aggregator-%"
excludeJobs: []
